_target_: src.models.butterfly_module.GraceLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: src.models.components.butterfly_net.ButterflyNet
  input_size1: 12
  hidden_size1:
    - 512
    - 256
  output_size1: 12
  latent_size: 6
  input_size2: 12
  hidden_size2:
    - 512
    - 256
  output_size2: 12
  dropout: 0.5
  

# compile model for faster training with pytorch 2.0
compile: false

# latent loss epsilon
epsilon: 0.15
