_target_: src.models.fk_module.GraceLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: src.models.components.fk_net.FKNet
  input_size: 12
  hidden_size1:
    - 512
    - 256
  latent_size: 6
  hidden_size2:
    - 512
    - 256
  output_size: 12
  dropout: 0.5
  

# compile model for faster training with pytorch 2.0
compile: false
