_target_: src.models.grace_module.GraceLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  input_size: 6
  output_size: 2
  hidden_size: 2
  hidden_nodes: 128
  

# compile model for faster training with pytorch 2.0
compile: false
