_target_: src.models.sfk_module.GraceLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: src.models.components.sfk_net.FKNet
  input_size: 6
  hidden_size:
    - 1024
    - 1024

  output_size: 12
  dropout: 0.1
  

# compile model for faster training with pytorch 2.0
compile: false
